### ISSUE TITLE
Build process is broken

### ISSUE THREAD

**Issue by johannesjh** [aumayr/fava-electron#4]
Hi,

I was interested to give fava-electron a try, but found the build process was broken.

First, I found I had to replace the fava repo URL, and I additionally specified a shallow clone to speed things up:

```
build/fava:
	git clone --depth 1 git@github.com:beancount/fava.git build/fava
```

Then I got another error and found I had to install pyinstaller in order to get the stuff to work.

```
pip3 install pyinstaller
```

Then I got a stacktrace (see attached file [stacktrace.txt](https://github.com/aumayr/fava-electron/files/717331/stacktrace.txt) that I don't quite understand.

Could you help to update/fix the repo and get things running properly?
thx, Johannes

**Comment by yagebu** [comment]
The build should be fixed now (up to the PyInstaller error). That seems to be due to Pyinstaller not supporting Python 3.6 yet.

You could add a symlink to the `fava` executable at `app/bin/fava` (or copy it there) to get started without it.

**Comment by johannesjh** [comment]
Thank you,that's great! 

Now slightly off-topic, since this has more to do with building fava than fava-electron: 

- Which version of Python are you using to build fava's `pyinstaller` target? 
- Are you running the build from within a virtualenv? (I tried both but got the same error described below)

Since pyinstaller is not yet compatible with python3.6, I switched back to python 3.5 using `brew switch python3 3.5.2_3`. I then tried to build fava's pyinstaller target (directly or from fava-electron), but I get a syntax error in jinja2:

```
4324 INFO: Processing pre-find module path hook   distutils
4329 INFO: distutils: retargeting to non-venv dir '/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils'
Traceback (most recent call last):
  File "/Users/johannes/repos/beancount/virtualenv/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/Users/johannes/repos/beancount/virtualenv/lib/python3.5/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
[...]
  File "/Users/johannes/repos/beancount/virtualenv/lib/python3.5/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2164, in _load_module
    co = compile(co_ast, pathname, 'exec', 0, True)
  File "/Users/johannes/repos/beancount/virtualenv/lib/python3.5/site-packages/jinja2/asyncsupport.py", line 35
    yield event
              ^
SyntaxError: 'yield' inside async function
make: *** [pyinstaller] Error 1
```

...compare the full [stacktrace.txt](https://github.com/aumayr/fava-electron/files/717778/stacktrace.txt)

**Comment by yagebu** [comment]
To build binaries for both Mac OS and Linux, I used Vagrant. It's been a while since I've used the `pyinstaller` target and it used to work back then (both in Virtualenv and when globally installed)...

**Comment by johannesjh** [comment]
I tried to fix how binaries are built, see https://github.com/beancount/fava/pull/494

**Comment by johannesjh** [comment]
Thank you for fixing and improving the build process. It is unfortunately broken again. Two problems:

1. Fava's makefile has no target `pyinstaller`. This is easily fixed. I am sending pull request https://github.com/aumayr/fava-electron/pull/5.
2. `fava/__init.py__` reads the version number from SCM. This fails when running the binary created by pyinstaller.

**Comment by johannesjh** [comment]
thank you for merging #5. 

I found a fix for the second issue that I mentioned above, i.e., that `fava/__init.py__` fails when running as binary created by pyinstaller. See pull request https://github.com/beancount/fava/pull/1035 

The build is now working locally on my machine, and I am currently preparing another pull request with changes for this repository.

**Comment by aumayr** [comment]
@johannesjh I would happily share maintainership of this repo - I am not actively using Fava via Electron, so if you do maybe you are interested in joining as a maintainer?

**Comment by johannesjh** [comment]
Thank you, yes, I'd be interested. 

I find the simplicity of a desktop app very appealing. (In contrast, the current user experience feels more like setting up a programming environment).

**Comment by johannesjh** [comment]
Btw, did you use to generate a single executable file using pyinstaller?, or multiple files? I currently get a `cli` binary, as well as many `.so` shared object library files.

**Comment by yagebu** [comment]
@johannesjh: This repo probably should have been deleted in 2017... The code was merged into the main Fava repository back then and maintained there until 2018. So it would be better to continue with the code there instead of the slightly more outdated code here.

**Comment by johannesjh** [comment]
hm, I am not sure if this is entirely correct. It appears to me that the electron gui code was deleted from main fava repository in a commit `gui remove` https://github.com/beancount/fava/commit/b6e1e73cdb94a7a9c9a85841339997f7bc92dead

**Comment by yagebu** [comment]
Yes, it was removed, that's why I wrote

> [...] and maintained there until 2018.

**Comment by sulemankm** [comment]
I have to do `npm install request --save` to get it working.  So may be the following lines should already be in the package.json file.

`  
"dependencies": {
    "request": "^2.88.0"
  }
`

I'musing python 3.7+.

**Comment by yagebu** [comment]
@johannesjh: If you want to actively use and maintain this, I'd be open to having this in the main repository (in the contrib folder). Then you can revert the commit removing the GUI and don't have to start with the outdated code here.

**Comment by johannesjh** [comment]
Thank you! I think I'll revert the commit in a branch in a forked repo and see how far I can get. I want to avoid what happened last week when I was overly optimistic and sent immature pull requests. I think it will be better if I start developing and using the electron app for a while. Once it is in a usable state I'd be glad if we can merge the feature back into the official repo.
